AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    82b1401e-a882-4588-8d67-4f113341372d:
      size:
        width: 60
        height: 60
      position:
        x: 217
        'y': 131
      z: 0
      embeds: []
    ac57c9c7-fe46-4d39-a7ce-74a76948de6c:
      size:
        width: 60
        height: 60
      position:
        x: 420
        'y': 200
      z: 0
      embeds: []
      dependson:
        - c5709a19-bfa2-4ed4-844a-8e062686b9cb
    c5709a19-bfa2-4ed4-844a-8e062686b9cb:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 309
      z: 0
      embeds: []
      dependson:
        - 82b1401e-a882-4588-8d67-4f113341372d

Resources:
  S3NakedStaticWebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: bucket-name-002
      WebsiteConfiguration:
        #        ErrorDocument: error.html
        #        IndexDocument: index.html
        RedirectAllRequestsTo:
          HostName: !Join
            - ''
            - - 'www.'
              - 'bucket-name-002'
      Tags:
        - Key: Created By
          Value: Thirumal
        - Key: Created Using
          Value: Cloud Formation
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c5709a19-bfa2-4ed4-844a-8e062686b9cb

  S3StaticWebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join
        - ''
        - - 'www.'
          - !Ref S3NakedStaticWebsiteBucket
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
      Tags:
        - Key: Created By
          Value: Thirumal
        - Key: Created Using
          Value: Cloud Formation
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 82b1401e-a882-4588-8d67-4f113341372d
    DependsOn:
      - S3NakedStaticWebsiteBucket
  S3PublicAccessPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3StaticWebsiteBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3StaticWebsiteBucket
                - /*
            Principal: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ac57c9c7-fe46-4d39-a7ce-74a76948de6c
    DependsOn:
      - S3StaticWebsiteBucket

