# Builder
# @author Thirumal
# @Created on 07/10/2020
AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    82b1401e-a882-4588-8d67-4f113341372d:
      size:
        width: 60
        height: 60
      position:
        x: 217
        'y': 131
      z: 0
      embeds: []
    ac57c9c7-fe46-4d39-a7ce-74a76948de6c:
      size:
        width: 60
        height: 60
      position:
        x: 370
        'y': 70
      z: 0
      embeds: []
      dependson:
        - c5709a19-bfa2-4ed4-844a-8e062686b9cb
        - 82b1401e-a882-4588-8d67-4f113341372d
    c5709a19-bfa2-4ed4-844a-8e062686b9cb:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 309
      z: 0
      embeds: []
      dependson:
        - 82b1401e-a882-4588-8d67-4f113341372d
    640de22f-55bf-475f-b395-c53310d40d93:
      size:
        width: 140
        height: 140
      position:
        x: 400
        'y': 210
      z: 0
      embeds:
        - 60bd4cf8-7406-4a1e-b9bc-a45ddf051058
      dependson:
        - ac57c9c7-fe46-4d39-a7ce-74a76948de6c
    60bd4cf8-7406-4a1e-b9bc-a45ddf051058:
      size:
        width: 60
        height: 60
      position:
        x: 446.95572295336916
        'y': 255.98893816829448
      z: 1
      parent: 640de22f-55bf-475f-b395-c53310d40d93
Parameters:
  bucketName:
    Description: Static Website / Bucket Name
    Type: String
Mappings:
  bucket:
    nonWwwBucket:
      name: bucketi-namoiwee-005.com
Resources:
  S3NonWWWStaticWebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref bucketName
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Join
            - ''
            - - www.
              - !Ref bucketName
      Tags:
        - Key: Created By
          Value: Thirumal
        - Key: Created Using
          Value: Cloud Formation
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c5709a19-bfa2-4ed4-844a-8e062686b9cb
  S3WWWStaticWebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join
        - ''
        - - www.
          - !Ref S3NonWWWStaticWebsiteBucket
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
      Tags:
        - Key: Created By
          Value: Thirumal
        - Key: Created Using
          Value: Cloud Formation
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 82b1401e-a882-4588-8d67-4f113341372d
    DependsOn:
      - S3NonWWWStaticWebsiteBucket
  S3PublicAccessPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3WWWStaticWebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3WWWStaticWebsiteBucket
                - /*
            Principal: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ac57c9c7-fe46-4d39-a7ce-74a76948de6c
    DependsOn:
      - S3WWWStaticWebsiteBucket
  WebsiteInHostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: !Ref S3NonWWWStaticWebsiteBucket
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 640de22f-55bf-475f-b395-c53310d40d93
    DependsOn:
      - S3PublicAccessPolicy
  R53RSS3ARecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: !Ref S3WWWStaticWebsiteBucket
      AliasTarget:
        DNSName: s3-website.ap-south-1.amazonaws.com # Must be just regional S3 website end point
        EvaluateTargetHealth: false
        HostedZoneId: !Ref WebsiteInHostedZone
      Type: A
      HostedZoneId: !Ref WebsiteInHostedZone
      #TTL: '900'
#      ResourceRecords:
#        - !Join
#          - ''
#          - - !Ref S3WWWStaticWebsiteBucket
#            - .s3-website.ap-south-1.amazonaws.com
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 60bd4cf8-7406-4a1e-b9bc-a45ddf051058
