# Builder
# Thirumal: https://twitter.com/_Thirumal
# Give Parameter bucket name : xyz.insolvencysoftware.in
AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    881adc88-6b74-45e9-9321-73dcdeabe536:
      size:
        width: 60
        height: 60
      position:
        x: 194
        'y': 142
      z: 0
      embeds: []
    cc784c95-7fcb-47da-b7c0-e90fd270f410:
      size:
        width: 60
        height: 60
      position:
        x: 414
        'y': 146
      z: 0
      embeds: []
      dependson:
        - 881adc88-6b74-45e9-9321-73dcdeabe536
    c527befd-a5ce-4e29-a662-bc951d668878:
      size:
        width: 60
        height: 60
      position:
        x: 620
        'y': 150
      z: 0
      embeds: []
      dependson:
        - cc784c95-7fcb-47da-b7c0-e90fd270f410
    698d1136-5e9a-4761-a7ae-e637c2e39f08:
      source:
        id: c527befd-a5ce-4e29-a662-bc951d668878
      target:
        id: cc784c95-7fcb-47da-b7c0-e90fd270f410
      z: 11
Parameters:
  bucketName:
    Description: Static Website / Bucket Name
    Type: String

Resources:
  S3SubDomainBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref 'bucketName'
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
      Tags:
        - Key: Created By
          Value: Thirumal
        - Key: Created Using
          Value: Cloud Formation
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 881adc88-6b74-45e9-9321-73dcdeabe536
  S3SubDomainPublicAccessPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3SubDomainBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3SubDomainBucket
                - /*
            Principal: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: cc784c95-7fcb-47da-b7c0-e90fd270f410
    DependsOn:
      - S3SubDomainBucket
  CFSubDomainDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
             - GET
             - HEAD
             - OPTIONS
          CachedMethods:
             - GET
             - HEAD
          TargetOriginId: !Ref 'S3SubDomainBucket'
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
#        CacheBehaviors:
#          AllowedMethods:
#             - GET
#             - HEAD
#             - OPTIONS
#          CachedMethods:
#             - GET
#             - HEAD
#          PathPattern: /*
#          TargetOriginId: !Ref 'S3SubDomainBucket'
#          ViewerProtocolPolicy: redirect-to-https
        Comment: Sub Domain created by cloud formation
        Enabled: yes
        HttpVersion: http2
        IPV6Enabled: yes
#        OriginGroups:
#          OriginGroups
        Origins:
          - DomainName: !Join
              - ''
              - - !Ref 'S3SubDomainBucket'
                - '.s3-website.ap-south-1.amazonaws.com'
            Id: !Ref 'S3SubDomainBucket'
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
#          - S3OriginConfig:
#             S3OriginConfig
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:597991982472:certificate/b4e34784-11fc-4c34-b75b-7135ac46c817
#          CloudFrontDefaultCertificate: false
#          IamCertificateId: String
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only

    Metadata:
      'AWS::CloudFormation::Designer':
        id: c527befd-a5ce-4e29-a662-bc951d668878
    DependsOn:
      - S3SubDomainPublicAccessPolicy
