# Builder
# @author Thirumal
# @Created on 07/10/2020
AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    881adc88-6b74-45e9-9321-73dcdeabe536:
      size:
        width: 60
        height: 60
      position:
        x: 194
        'y': 142
      z: 0
      embeds: []
    cc784c95-7fcb-47da-b7c0-e90fd270f410:
      size:
        width: 60
        height: 60
      position:
        x: 414
        'y': 146
      z: 0
      embeds: []
      dependson:
        - 881adc88-6b74-45e9-9321-73dcdeabe536
    c527befd-a5ce-4e29-a662-bc951d668878:
      size:
        width: 60
        height: 60
      position:
        x: 620
        'y': 150
      z: 0
      embeds: []
      dependson:
        - cc784c95-7fcb-47da-b7c0-e90fd270f410
    75a65570-b59a-462c-b536-88de6742aa3d:
      size:
        width: 60
        height: 60
      position:
        x: 500
        'y': 240
      z: 0
      dependson:
        - c527befd-a5ce-4e29-a662-bc951d668878
    e9a8335f-3a02-4b2c-b6c9-c1b60ad736aa:
      source:
        id: 75a65570-b59a-462c-b536-88de6742aa3d
      target:
        id: c527befd-a5ce-4e29-a662-bc951d668878
      z: 11
Parameters:
  bucketName:
    Description: Static Website / Bucket Name
    Type: String
  HostedZone:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
Resources:
  S3SubDomainBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref bucketName
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
      Tags:
        - Key: Created By
          Value: Thirumal
        - Key: Created Using
          Value: Cloud Formation
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 881adc88-6b74-45e9-9321-73dcdeabe536
  S3SubDomainPublicAccessPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3SubDomainBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3SubDomainBucket
                - /*
            Principal: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: cc784c95-7fcb-47da-b7c0-e90fd270f410
    DependsOn:
      - S3SubDomainBucket
  CFSubDomainDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: !Ref S3SubDomainBucket
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        Comment: Sub Domain created by cloud formation
        Enabled: yes
        HttpVersion: http2
        IPV6Enabled: yes
        Origins:
          - DomainName: !Join
              - ''
              - - !Ref S3SubDomainBucket
                - .s3-website.ap-south-1.amazonaws.com
            Id: !Ref S3SubDomainBucket
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        Aliases: [ !Ref bucketName ]
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:597991982472:certificate/b4e34784-11fc-4c34-b75b-7135ac46c817
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c527befd-a5ce-4e29-a662-bc951d668878
    DependsOn:
      - S3SubDomainPublicAccessPolicy
  R53CNameForSubDomain:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: !Ref S3SubDomainBucket
      Type: CNAME
      #HostedZoneName: !Join ['', [!Ref 'HostedZone', .]]
      HostedZoneId: Z08340141ZQLKPW4JWOKC
      TTL: '900'
      ResourceRecords:
        - !GetAtt CFSubDomainDistribution.DomainName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 75a65570-b59a-462c-b536-88de6742aa3d
    DependsOn:
      - CFSubDomainDistribution
